import SkillsList from "./SkillsList";
import SkillsListItem from "./SkillsListItem";

export default function SecondPage() {
  return (
    <div className="min-w-full flex flex-col items-center p-5">
      <h1 className="text-3xl sm:text-5xl self-start py-10 min mb-20">Technical Skills</h1>
      <div className="sm:flex w-5/6 py-5 gap-4">
        <SkillsList
          skillsListTitle="Languages"
          skillsListItems={
            <>
              <SkillsListItem
                skillName="Go"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/go/go-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="Python"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="JavaScript"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg"
              />
              <SkillsListItem
                skillName="TypeScript"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg"
              />
              <SkillsListItem
                skillName="HTML"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="CSS"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="Java"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="C"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg"
              />
              <SkillsListItem
                skillName="Lua"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/lua/lua-original.svg"
              />
            </>
          }
        />
        <SkillsList
          skillsListTitle="Frameworks & Libraries"
          skillsListItems={
            <>
              <SkillsListItem
                skillName="React"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="Next.js"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="TailwindCSS"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg"
              />
              <SkillsListItem
                skillName="MatPlotLib"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matplotlib/matplotlib-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="OpenCV"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/opencv/opencv-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="NumPy"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/numpy/numpy-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="Pandas"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pandas/pandas-original-wordmark.svg"
              />
              <SkillsListItem
                skillName="scikit-learn"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/scikitlearn/scikitlearn-original.svg"
              />
            </>
          }
        />
        <SkillsList
          skillsListTitle="Tools"
          skillsListItems={
            <>
              <SkillsListItem
                skillName="Git"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg"
              />
              <SkillsListItem
                skillName="Linux"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linux/linux-original.svg"
              />
              <SkillsListItem
                skillName="Emacs"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/emacs/emacs-original.svg"
              />
              <SkillsListItem
                skillName="Vim"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vim/vim-original.svg"
              />
              <SkillsListItem
                skillName="VSCode"
                skillIconLink="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/visualstudio/visualstudio-plain.svg"
              />
            </>
          }
        />
      </div>
    </div>
  );
}
